# Generated by Django 5.0.7 on 2024-08-16 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_tag_post_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(blank=True, max_length=150, unique=True),
        ),
    ]
